version: '3.8'
services:
  booking-rooms:
    build: .
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - bookingrooms_net
    depends_on:
      - db
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=StrongPassword123!
      - POSTGRES_DATABASE=booking-roomsdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - bookingrooms_net
volumes:
  pgdata:
    external: true
    name: booking-rooms-backup
networks:
    bookingrooms_net:
      driver : brigde